"""empty message

Revision ID: 7ed89ea04a46
Revises: e0910beaf6e3
Create Date: 2023-05-01 18:54:18.349125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed89ea04a46'
down_revision = 'e0910beaf6e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
