"""empty message

Revision ID: 94e7f84ca1a5
Revises: ba40e99c89d6
Create Date: 2023-05-01 19:31:09.342660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e7f84ca1a5'
down_revision = 'ba40e99c89d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
