from dotenv import load_dotenv
import os

load_dotenv()

DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_NAME = os.getenv('DB_NAME')
DB_HOST = os.getenv('DB_HOST')
DB_USER_TEST = os.getenv('DB_USER_TEST')
DB_PASSWORD_TEST = os.getenv('DB_PASSWORD_TEST')
DB_NAME_TEST = os.getenv('DB_NAME_TEST')

SMTP_HOST = os.getenv('SMTP_HOST')
SMTP_PORT = os.getenv('SMTP_PORT')
SMTP_USER = os.getenv('SMTP_USER')
SMTP_PASSWORD = os.getenv('SMTP_PASSWORD')

SECRET_USER_AUTHENTICATION = os.getenv('SECRET_USER_AUTHENTICATION')
SECRET_USER_MANAGER = os.getenv('SECRET_USER_MANAGER')
SECRET_EMAIL_CONFIRMATION = os.getenv('SECRET_EMAIL_CONFIRMATION')
AUDIENCE_EMAIL_CONFIRMATION = os.getenv('AUDIENCE_EMAIL_CONFIRMATION')